pizzas/urls.py
from django.urls import path
from . import views

app_name = 'pizzas'
urlpatterns = [
    # Strona główna
    path('', views.index, name='index'),
    # Wyświetlenie wszystkich pizz
    path('pizzs/', views.pizzs, name='pizzs'),
    # API endpoints dla pizz
    path('pizzas_api/', views.PizzaList.as_view()),
    path('pizzas_api/<int:pk>', views.PizzaDetail.as_view()),
]

pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

pizzas/models.py
from django.db import models

# Create your models here.

PIZZA_SIZE = (
    ('S', 'mała'),
    ('M', 'średnia'),
    ('L', 'duża'),
    ('XXL', 'ogromna')
)


class Pizza(models.Model):
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    main_topping = models.CharField(max_length=40, default="ser")
    size = models.CharField(choices=PIZZA_SIZE, max_length=30, default='S')
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name} - {self.price} zł'

pizzas/views.py
from django.shortcuts import render
from .models import Pizza
from .serializers import PizzaSerializer
from rest_framework import generics, permissions


def index(request):
    return render(request, 'pizzas/index.html')


def pizzs(request):
    """Wyświetlenie wszystkich pizz"""
    pizzs = Pizza.objects.order_by('date_added')
    context = {'pizzs': pizzs}
    return render(request, 'pizzas/pizzs.html', context)


class PizzaList(generics.ListCreateAPIView):
    queryset = Pizza.objects.all()
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    serializer_class = PizzaSerializer


class PizzaDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Pizza.objects.all()
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    serializer_class = PizzaSerializer

pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}">Home</a> -
    <a href="{% url 'pizzas:pizzs' %}">Pizzunie</a>
</p>

{% block content %}{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}
<p>Zajebiste pizze </p>
{% endblock content %}

pizzas/templates/pizzas/pizzs.html
{% extends "pizzas/base.html" %}

{% block content %}
<p>Pizze:</p>

<ul>
    {% for pizza in pizzs %}
        <li> {{ pizza }}</li>
    {% empty %}
        <li>Nie została jeszcze dodana żadna pizza</li>
    {% endfor %}
</ul>

{% endblock content %}